# Generated by Django 5.2.15 on 2026-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
