# Generated by Django 5.2.15 on 2026-06-20 08:07

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_booked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showtime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='booked',
            index=models.Index(fields=['showtime'], name='movies_book_showtim_37e5e1_idx'),
        ),
        migrations.AddIndex(
            model_name='booked',
            index=models.Index(fields=['user'], name='movies_book_user_id_da0358_idx'),
        ),
        migrations.AddIndex(
            model_name='booked',
            index=models.Index(fields=['status'], name='movies_book_status_2d6512_idx'),
        ),
    ]
